* Base

** Programme minimal

#+BEGIN_SRC glsl
  void mainImage(vec2 coord, vec4 color) {
  }
#+END_SRC

** Commentaires

Les commentaires sont juste là pour aider les humains. La machine les ignores.

#+BEGIN_SRC glsl
  void mainImage(vec2 coord, vec4 color) {
    // Ceci est un commentaire.
  }
#+END_SRC

** Afficher une quelquechose

Il faut changer la variable ~color~. Soit avec =color = vec4(rouge,vert,bleu,alpha)= (on utilise jamais alpha, c'est la transparance)

Ou avec ~color.r = valeur~ pour changer uniqument le rouge par exemple.

Les valeurs sont entre 0 et 1.

#+BEGIN_SRC glsl
  void mainImage(vec2 coord, vec4 color) {
    // On commence avec du noir
    color = vec4(0.);
    // On ajoute du rouge
    color.r = 1.0;
    // Et puis un peu de bleu
    color.b = 0.3;
  }
#+END_SRC

** Coordonnées

   On peut soit utiliser differents systèmes de coordonnées selon ce que l'on veut.

*** Entre 0 et 800 pour x, et entre 0 et 450 pour y

    On utilise directement coord, avec coord.x et coord.y

*** Entre 0 et 1 pour x et y

    vec2 uv = coord / iResolution.xy; // <0,1>
  
    On utilise uv.x et uv.y

*** Entre -1 et 1 pour x et y

    Avantage: Le centre est le point (0,0)

    vec2 uv = 2 * (coord / iResolution.xy - 0.5); // <-1,1>

    On utilise uv.x et uv.y

* Formes

** Rectanges

** Ovales
